version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
   image: confluentinc/cp-kafka:7.4.4
   container_name: kafka
   depends_on:
    - zookeeper
   ports:
    - 9092:9092 
    - 29092:29092 
   environment:
    KAFKA_BROKER_ID: 1
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    KAFKA_LISTENERS: LISTENER_BOB://kafka:29092,LISTENER_FRED://kafka:9092
    KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka:29092,LISTENER_FRED://localhost:9092
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
    KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - kafka-connect
      - schema-registry
      - zookeeper
      - json-server
    restart: on-failure


  json-server:
    image: imanimorepo/jsonserver:latest
    volumes:
      - ./db.json:/data/db.json
    ports:
      - "8080:8080"
    command: --watch /data/db.json

  kafka-connect:
    image: confluentinc/cp-kafka-connect:7.4.4
    container_name: kafka-connect
    ports:
      - 8083:8083
    depends_on:
      - kafka
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:29092
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_GROUP_ID: "connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_TOPIC_CREATION_ENABLE: 'true'
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_REST_PORT: 8083
      CONNECT_PLUGIN_PATH: "/usr/share/java/kafka-connect-http,/usr/share/java/kafka-connect-jdbc,/etc/kafka-connect/connectors"
    volumes:
      - /home/acha/kafka-connect-plugins/confluentinc-kafka-connect-http-source:/usr/share/java/kafka-connect-http
      - /home/acha/Downloads/confluentinc-kafka-connect-jdbc-10.7.12:/usr/share/java/kafka-connect-jdbc
      - ./db.json:/data/db.json

  schema-registry:
    image: confluentinc/cp-schema-registry:7.2.1
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092  
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-datastore:/var/lib/postgresql/data

volumes:
  postgres-datastore:
